export const COLORS = {
	BG: '#FCFCFC',
	ACCENT_BLACK: {
		BLACK_LIGHT: '#272B30',
		BLACK_DARK: '#1A1D1F',
	},
	ACCENT_GRAY: '#6f767e',
	ACCENT_WHITE: '#f4f4f4',
	ACCENT_PURPLE: '#999DFF',
	ACCENT_GREEN: '#60CA57',
} as const;
